app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', function () {
    if (\Auth::check()) {
        return redirect()->route('dashboard');
    }

    return view('welcome')
        ->withTitle('Laratest');
});

Route::get('test', function () {
    return view('test');
});

Route::auth();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::put('book/{book}/updateable', 'BookController@updateable')->name('book.updateable');
    Route::post('book/upload/{book}', 'BookController@upload')->name('book.upload');
    Route::resource('book', 'BookController');

    Route::resource('user', 'UserController');
});

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Book\UpdateableRequest;
use App\Http\Requests\Book\UploadRequest;
use App\Http\Requests\Book\ValidationRequest;
use App\Laratest\Book;
use Auth;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function __construct()
    {
        abort_if(!Auth::user()->hasRole(['super_admin', 'admin', 'user']), 500, trans('book.permissionDenied'));
    }

    /**
     * Display a listing of the book.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(!Auth::user()->can('book-show'), 500, trans('book.permissionDenied'));

        $books = Book::orderBy('title', 'ASC')
            ->when(request('q'), function ($query) {
                return $query->where('title', 'LIKE', '%' . request('q') . '%')
                    ->orWhere('author', 'LIKE', '%' . request('q') . '%');
            })
            ->paginate($limit = 20);

        return view('contents.books.index', compact('books'))
            ->withLimit($limit)
            ->withTitle(empty(request('q')) ? trans('book.title') : trans('book.resultFor', ['query' => request('q')]))
            ->withSubTitle(trans('book.subtitle'))
            ->withSearch(true);
    }

    /**
     * Show the form for creating a new book.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(!Auth::user()->can('book-create'), 500, trans('book.permissionDenied'));

        return view('contents.books.create')
            ->withTitle(trans('book.create'));
    }

    /**
     * Store a newly created book in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidationRequest $request)
    {
        abort_if(!Auth::user()->can('book-create'), 500, trans('book.permissionDenied'));

        $book = \DB::transaction(function () use ($request) {
            $book = new Book;

            $book->slug = str_slug($request->title);
            $book->title = $request->title;
            $book->author = $request->author;

            $book->save();

            if (!empty($request->image) and $request->file('image')->isValid()) {
                $image = $this->uploadImage($book, $request);

                $book->attachMedia($image, ['original', 'thumbnail']);
            }

            return $book;
        });

        return redirect()
            ->route(Auth::user()->can('book-show') ? 'book.index' : 'book.create')
            ->withSuccess(trans('book.message.created', ['title' => $book->title]));
    }

    /**
     * Display the specified book.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort_if(!Auth::user()->can('book-show'), 500, trans('book.permissionDenied'));

        $book = Book::findOrFail($id);

        if (request()->ajax()) {
            return [
                'isSuccess' => true,
                'content'   => [
                    'id'     => $book->id,
                    'title'  => $book->title,
                    'author' => $book->author,
                    'image'  => $book->hasMedia('thumbnail') ? $book->firstMedia('thumbnail')->getUrl() : '',
                ],
            ];
        }

        return view('contents.books.show', compact('book'))
            ->withTitle($book->title)
            ->withSubTitle(trans('book.writenBy', ['author' => $book->author]));
    }

    /**
     * Show the form for editing the specified book.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort_if(!Auth::user()->can('book-update'), 500, trans('book.permissionDenied'));

        $book = Book::findOrFail($id);

        return view('contents.books.edit', compact('book'))
            ->withTitle($book->title)
            ->withSubTitle(trans('book.writenBy', ['author' => $book->author]));
    }

    /**
     * Update the specified book in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ValidationRequest $request, $id)
    {
        abort_if(!Auth::user()->can('book-update'), 500, trans('book.permissionDenied'));

        $book = Book::findOrFail($id);

        $book = \DB::transaction(function () use ($book, $request) {
            $book->title = $request->title;
            $book->author = $request->author;

            $book->save();

            if (!empty($request->image) and $request->file('image')->isValid()) {
                $image = $this->uploadImage($book, $request);

                // sync media
                $book->syncMedia($image, ['original', 'thumbnail']);
            }

            return $book;
        });

        return redirect(route('book.edit', ['book' => $book->id]))
            ->withSuccess(trans('book.message.updated', ['title' => $book->title]));
    }

    /**
     * Remove the specified book from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        abort_if(!Auth::user()->can('book-delete'), 500, trans('book.permissionDenied'));

        $book = Book::findOrFail($id);

        if ($book->delete() === true) {
            return redirect()
                ->route('book.index')
                ->withSuccess(trans('book.message.deleted'));
        }

        return redirect()->back();
    }

    /**
     * @param UploadRequest $request
     * @param $id
     */
    public function upload(UploadRequest $request, $id)
    {
        $book = Book::findOrFail($id);

        // upload cover image
        $cover = $this->uploadImage($book, $request);

        // attach to book
        $book->syncMedia($cover, ['original', 'thumbnail']);

        return [
            'isSuccess' => true,
            'message'   => trans('book.message.uploaded', ['title' => $book->title]),
            'content'   => [
                'title' => $book->title,
                'image' => $book->firstMedia('thumbnail')->getUrl(),
            ],
        ];
    }

    /**
     * @param UpdateableRequest $request
     * @param $id
     */
    public function updateable(UpdateableRequest $request, $id)
    {
        $book = Book::findOrFail($id);

        $column = $request->name;

        $columns = collect($book->getAttributes())->only(['title', 'author']);

        if (!$columns->has($column)) {
            return [
                'isSuccess' => false,
                'message'   => trans('book.message.fieldUnavailable', ['field' => $column]),
            ];
        }

        $book->$column = $request->value;

        return [
            'isSuccess' => $book->save(),
            'message'   => trans('book.message.updated'),
            'content'   => [
                'id'        => $book->id,
                'updatedAt' => $book->updated_at->format('Y-m-d H:i'),
            ],
        ];
    }

    /**
     * @param $book
     * @param $request
     * @return mixed
     */
    private function uploadImage($book, $request)
    {
        $image = \Media::fromSource($request->file('image'))
            ->useFilename($book->slug)
            ->toDestination('media', 'book')
            ->upload();

        if (request()->isMethod('put')) {
            \Media::update($image);
        }

        return $image;
    }
}

resources/views/contents/books/create.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('book.create')</h3>
    </div>

    <form action="{{ route('book.store') }}" method="post" name="form-create" enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('post') }}

    <div class="box-body">
        @include('contents.books.form')
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary">@lang('book.btn.save')</button>
        <a href="{{ route('book.index') }}" class="btn btn-default">@lang('book.btn.back')</a>
    </div>

    </form>

</div>
@endsection

resources/views/contents/books/edit.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('book.edit')</h3>
    </div>

    <form action="{{ route('book.update', ['book' => $book->id]) }}" method="post" name="form-edit"  enctype="multipart/form-data">
    {{ csrf_field() }}
    {{ method_field('put') }}

    <div class="box-body">
        @include('contents.books.form', compact('book'))
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary">@lang('book.btn.save')</button>
        <a href="{{ route('book.index') }}" class="btn btn-default">@lang('book.btn.back')</a>
    </div>

    </form>

</div>
@endsection

resources/views/contents/books/form.blade.php
<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
    <label class="control-label">@lang('book.form.title')</label>
    <input type="text" name="title" class="form-control" value="{{ old('title', isset($book) ? $book->title : '') }}">
    <span class="help-block">{{ $errors->first('title') }}</span>
</div>

<div class="form-group {{ $errors->has('author') ? 'has-error' : '' }}">
    <label class="control-label">@lang('book.form.author')</label>
    <input type="text" name="author" class="form-control" value="{{ old('author', isset($book) ? $book->author : '') }}">
    <span class="help-block">{{ $errors->first('author') }}</span>
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
    <label class="control-label">@lang('book.form.image')</label>
    <input type="file" name="image">
    <span class="help-block">{{ $errors->first('image') }}</span>
</div>

resources/views/contents/books/index.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('book.title')</h3>
    </div>

    <div class="box-body">
        <p>
            @if (auth()->user()->can('book-create'))
            <a href="{{ route('book.create') }}" class="btn btn-primary btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.create')">
                <i class="fa fa-plus"></i>
            </a>
            @endif
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>@lang('book.form.slug')</th>
                    <th>@lang('book.form.title')</th>
                    <th>@lang('book.form.author')</th>
                    <th>@lang('book.form.created')</th>
                    <th>@lang('book.form.updated')</th>
                    <th class="text-right">@lang('book.action')</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($books as $book)
                    <tr>
                        <td>{{ $book->slug }}</td>
                        <td>
                            <a href="#" class="book-title" data-name="title" data-value="{{ $book->title }}" data-type="text" data-pk="{{ $book->id }}" data-url="{{ route('book.updateable', ['book' => $book->id]) }}" data-title="@lang('book.form.title')">
                                {{ $book->title }}
                            </a>
                        </td>
                        <td>
                            <a href="#" class="book-author" data-name="author" data-value="{{ $book->author }}" data-type="text" data-pk="{{ $book->id }}" data-url="{{ route('book.updateable', ['book' => $book->id]) }}" data-title="@lang('book.form.author')">
                                {{ $book->author }}
                            </a>
                        </td>
                        <td>
                            @if (! empty($book->created_at))
                                {{ $book->created_at->format('Y-m-d H:i') }}
                            @endif
                        </td>
                        <td class="updated-{{ $book->id }}">
                            @if (! empty($book->updated_at))
                                {{ $book->updated_at->format('Y-m-d H:i') }}
                            @endif
                        </td>
                        <td class="text-right">
                            <a href="{{ route('book.upload', ['book' => $book->id]) }}" class="btn btn-default btn-sm upload" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.uploadImage')" data-url="{{ route('book.show', ['book' => $book->id]) }}">
                                <i class="fa fa-upload"></i>
                            </a>

                            @if (auth()->user()->can('book-show'))
                            <a href="{{ route('book.show', ['book' => $book->id]) }}" class="btn btn-default btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.show')">
                                <i class="fa fa-book"></i>
                            </a>
                            @endif

                            @if (auth()->user()->can('book-update'))
                            <a href="{{ route('book.edit', ['book' => $book->id]) }}" class="btn btn-warning btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.edit')">
                                <i class="fa fa-edit"></i>
                            </a>
                            @endif

                            @if (auth()->user()->can('book-delete'))
                            <a href="{{ route('book.destroy', ['book' => $book->id]) }}" class="btn btn-danger btn-sm delete" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.delete')">
                                <i class="fa fa-trash"></i>
                            </a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        @if ($books->total() <= 0)
            <div class="alert alert-info">@lang('book.noBook')</div>
        @endif
    </div>

    @if ($books->total() >= $limit)
    <div class="box-footer">
        {{ $books->links() }}
    </div>
    @endif

</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-delete">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@lang('book.deleteConfirm')</h4>
            </div>

            <form action="" method="post" name="form-delete" id="form-delete">
            {{ csrf_field() }}
            {{ method_field('delete') }}

            <div class="modal-body">
                <p>@lang('book.deleteMessage')</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-times"></i>
                </button>
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash"></i>
                </button>
            </div>

            </form>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-upload">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@lang('book.uploadConfirm')</h4>
            </div>

            <form action="" method="post" name="form-upload" id="form-upload" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('post') }}

            <div class="modal-body">
                <div class="validation"></div>
                <div class="image-thumbnail"></div>

                <div class="form-group">
                    <label class="control-label">@lang('book.form.image')</label>
                    <input type="file" name="image" id="cover-image">
                </div>
            </div>

            <div class="modal-footer">
                <i class="fa fa-spinner fa-spin preloader"></i>
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-times"></i>
                </button>
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-upload"></i>
                </button>
            </div>

            </form>
        </div>
    </div>
</div>
@endsection

@push('css')
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet"/>
@endpush

@push('js')
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
@endpush

@push('script')
    <script>
        $(function(){
            $('.preloader, .validation').hide()

            $('.book-title, .book-author').editable({
                send: 'always',
                ajaxOptions: {
                    type: 'put'
                },
                params: function(params) {
                    params._token = '{{ csrf_token() }}'

                    return params
                },
                success: function(response) {
                    if (response.isSuccess == false) {
                        return response.message
                    }

                    $('.updated-'+response.content.id).text(response.content.updatedAt)
                }
            })

            $('a.delete').click(function(){
                $('#modal-delete').modal('show')

                $('#form-delete').attr('action', $(this).attr('href'))

                return false
            })

            $('a.upload').click(function(){
                $('.image-thumbnail').empty()
                $('.validation').hide()

                $.get($(this).attr('data-url'), null, function(response){
                    if (response.isSuccess == true && response.content.image != '') {
                        $('.image-thumbnail')
                            .html('<figure><img src="'+response.content.image+'" alt="'+response.content.title+'" class="img-responsive"> <figcaption>'+response.content.title+'</figcaption></figure><hr>')
                            .show()
                    }
                })

                $('#modal-upload').modal('show')

                $('#form-upload').attr('action', $(this).attr('href'))

                return false
            })

            $('#form-upload').submit(function(){
                var file = $('#cover-image').prop('files')[0]
                var data = new FormData();
                data.append('_token', '{{ csrf_token() }}')
                data.append('image', file)

                $('.preloader').show()

                $.ajax({
                    url: $(this).attr('action'),
                    type: $(this).attr('method'),
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function(response, status, xhr) {
                        if (response.isSuccess == true) {
                            $('.validation')
                                .text('')
                                .addClass('alert alert-success')
                                .text(response.message)
                                .show()

                            $('.image-thumbnail')
                                .html('<figure><img src="'+response.content.image+'" alt="'+response.content.title+'" class="img-responsive"> <figcaption>'+response.content.title+'</figcaption></figure><hr>')
                            .show()
                        }
                        else {
                            $('.validation')
                                .text('')
                                .addClass('alert alert-danger')
                                .text('@lang('book.message.error')')
                                .show()
                        }

                        $('.preloader').hide()
                    }
                })

                return false
            })
        })
    </script>
@endpush

resources/views/contents/books/show.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('book.show')</h3>
    </div>

    <div class="box-body">
        <div class="row">
            <div class="col-md-2">
                @if ($book->hasMedia('original'))
                    <img src="{{ $book->firstMedia('original')->getUrl() }}" class="img-responsive img-rounded">
                @else
                    <p>@lang('book.noImage')</p>
                @endif

            </div>
            <div class="col-md-10">
                <table class="table">
                    <tr>
                        <td>@lang('book.form.title')</td>
                        <td>{{ $book->title }}</td>
                    </tr>
                    <tr>
                        <td>@lang('book.form.author')</td>
                        <td>{{ $book->author }}</td>
                    </tr>
                    @if (! empty($book->created_at))
                    <tr>
                        <td>@lang('book.form.created')</td>
                        <td>{{ $book->created_at->format('Y-m-d H:i') }}</td>
                    </tr>
                    @endif

                    @if(! empty($book->updated_at))
                    <tr>
                        <td>@lang('book.form.updated')</td>
                        <td>{{ $book->updated_at->format('Y-m-d H:i') }}</td>
                    </tr>
                    @endif
                </table>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <a href="{{ route('book.edit', ['book' => $book->id]) }}" class="btn btn-primary" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.edit')">
            <i class="fa fa-edit"></i>
        </a>
        <a href="{{ route('book.index') }}" class="btn btn-default" type="button" data-toggle="tooltip" data-original-title="@lang('book.btn.back')">
            <i class="fa fa-arrow-left"></i>
        </a>
    </div>

</div>
@endsection