app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', function () {
    if (\Auth::check()) {
        return redirect()->route('dashboard');
    }

    return view('welcome')
        ->withTitle('Laratest');
});

Route::get('test', function () {
    return view('test');
});

Route::auth();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::put('book/{book}/updateable', 'BookController@updateable')->name('book.updateable');
    Route::post('book/upload/{book}', 'BookController@upload')->name('book.upload');
    Route::resource('book', 'BookController');

    Route::resource('user', 'UserController');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;
    // use HasRole;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\User\ValidationRequest;
use App\Laratest\Role;
use App\User;

class UserController extends Controller
{
    public function __construct()
    {
        abort_if(!\Auth::user()->hasRole('super_admin'), 500, trans('user.permissionDenied'));
    }

    /**
     * Display a listing of the user.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('name', 'ASC')
            ->when(request('q'), function ($query) {
                return $query->where('name', 'LIKE', '%' . request('q') . '%');
            })
            ->paginate($limit = 20);

        return view('contents.users.index', compact('users'))
            ->withTitle(trans('user.title'))
            ->withSubTitle(trans('user.subtitle'))
            ->withLimit($limit)
            ->withSearch(true);
    }

    /**
     * Show the form for creating a new user.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::orderBy('display_name', 'ASC')->get();

        return view('contents.users.create', compact('roles'))
            ->withTitle(trans('user.create'));
    }

    /**
     * Store a newly created user in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidationRequest $request)
    {
        $role = Role::findOrFail($request->role);

        $user = \DB::transaction(function () use ($request, $role) {
            $user = new User;

            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->remember_token = $request->_token;

            $user->save();

            // attach to role
            $user->attachRole($role);

            return $user;
        });

        return redirect()
            ->route('user.index')
            ->withSuccess(trans('user.message.created', ['name' => $user->name]));
    }

    /**
     * Display the specified user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('contents.users.show', compact('user'))
            ->withTitle($user->name);
    }

    /**
     * Show the form for editing the specified user.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $roles = Role::orderBy('display_name')->get();

        return view('contents.users.edit', compact('user', 'roles'))
            ->withTitle(trans('user.edit'));
    }

    /**
     * Update the specified user in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ValidationRequest $request, $id)
    {
        $user = User::findOrFail($id);

        $role = Role::findOrFail($request->role);

        \DB::transaction(function () use ($user, $role, $request) {
            $user->name = $request->name;

            $user->save();

            // syn roles
            $user->roles()->sync([$role->id]);
        });

        return redirect()
            ->route('user.index')
            ->withSuccess(trans('user.message.edited'));
    }

    /**
     * Remove the specified user from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        if ($user->delete() === true) {
            return redirect()
                ->route('user.index')
                ->withSuccess(trans('user.message.deleted'));
        }

        return redirect()->back();
    }
}

resources/views/contents/users/create.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('user.create')</h3>
    </div>

    <form action="{{ route('user.store') }}" method="post" name="form-create">
    {{ csrf_field() }}
    {{ method_field('post') }}

    <div class="box-body">
        @include('contents.users.form')
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary">@lang('user.btn.save')</button>
        <a href="{{ route('user.index') }}" class="btn btn-default">@lang('user.btn.back')</a>
    </div>

    </form>

</div>
@endsection

resources/views/contents/users/edit.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('user.edit')</h3>
    </div>

    <form action="{{ route('user.update', ['user' => $user->id]) }}" method="post" name="form-edit">
    {{ csrf_field() }}
    {{ method_field('put') }}

    <div class="box-body">
        @include('contents.users.form', compact('user', 'roles'))
    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary">@lang('user.btn.save')</button>
        <a href="{{ route('user.index') }}" class="btn btn-default">@lang('user.btn.back')</a>
    </div>

    </form>

</div>
@endsection

resources/views/contents/users/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    <label class="control-label">@lang('user.form.name')</label>
    <input type="text" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}">
    <span class="help-block">{{ $errors->first('name') }}</span>
</div>

<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
    <label class="control-label">@lang('user.form.email')</label>
    <input type="text" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}">
    <span class="help-block">{{ $errors->first('email') }}</span>
</div>

<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
    <label class="control-label">@lang('user.form.password')</label>
    <input type="password" name="password" class="form-control">
    <span class="help-block">{{ $errors->first('password') }}</span>
</div>

<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    <label class="control-label">@lang('user.form.role')</label>
    <select name="role" class="form-control">
    	@foreach($roles as $role)
    		<option value="{{ $role->id }}">{{ $role->display_name }}</option>
    	@endforeach
    </select>
    <span class="help-block">{{ $errors->first('name') }}</span>
</div>

resources/views/contents/users/index.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('user.title')</h3>
    </div>

    <div class="box-body">
        <p>
            <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.create')">
                <i class="fa fa-plus"></i>
            </a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>@lang('user.form.name')</th>
                    <th>@lang('user.form.email')</th>
                    <th>@lang('user.form.role')</th>
                    <th>@lang('user.form.created')</th>
                    <th>@lang('user.form.updated')</th>
                    <th class="text-right">@lang('user.action')</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($users as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->roles->implode('display_name', ', ') }}</td>
                        <td>
                            @if (! empty($user->created_at))
                                {{ $user->created_at->format('Y-m-d H:i') }}
                            @endif
                        </td>
                        <td>
                            @if (! empty($user->updated_at))
                                {{ $user->updated_at->format('Y-m-d H:i') }}
                            @endif
                        </td>
                        <td class="text-right">
                            <a href="{{ route('user.show', ['book' => $user->id]) }}" class="btn btn-default btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.profile')">
                                <i class="fa fa-user"></i>
                            </a>

                            <a href="{{ route('user.edit', ['book' => $user->id]) }}" class="btn btn-warning btn-sm" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.edit')">
                                <i class="fa fa-edit"></i>
                            </a>

                            <a href="{{ route('user.destroy', ['book' => $user->id]) }}" class="btn btn-danger btn-sm delete" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.delete')">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        @if ($users->total() <= 0)
            <div class="alert alert-info">@lang('user.noUser')</div>
        @endif
    </div>

    @if ($users->total() >= $limit)
    <div class="box-footer">
        {{ $users->links() }}
    </div>
    @endif

</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal-delete">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">@lang('user.deleteConfirm')</h4>
            </div>

            <form action="" method="post" name="form-delete" id="form-delete">
            {{ csrf_field() }}
            {{ method_field('delete') }}

            <div class="modal-body">
                <p>@lang('user.deleteMessage')</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">
                    <i class="fa fa-times"></i>
                </button>
                <button type="submit" class="btn btn-danger">
                    <i class="fa fa-trash"></i>
                </button>
            </div>

            </form>
        </div>
    </div>
</div>
@endsection

@push('script')
    <script>
        $(function(){
            $('a.delete').click(function(){
                $('#modal-delete').modal('show')

                $('#form-delete').attr('action', $(this).attr('href'))

                return false
            })
        })
    </script>
@endpush

resources/views/contents/users/show.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('user.show')</h3>
    </div>

    <div class="box-body">
        <div class="row">
            <div class="col-md-2">
                <img src="https://www.gravatar.com/avatar/{{ md5($user->email) }}?s=150">
            </div>
            <div class="col-md-10">
                <table class="table">
                    <tr>
                        <td>@lang('user.form.name')</td>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <td>@lang('user.form.email')</td>
                        <td>{{ $user->email }}</td>
                    </tr>
                    <tr>
                        <td>@lang('user.form.role')</td>
                        <td>{{ $user->roles->implode('display_name', ', ') }}</td>
                    </tr>
                    <tr>
                        <td>@lang('user.form.created')</td>
                        <td>{{ $user->created_at->format('Y-m-d H:i') }}</td>
                    </tr>
                    <tr>
                        <td>@lang('user.form.updated')</td>
                        <td>{{ $user->updated_at->format('Y-m-d H:i') }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <a href="{{ route('user.index') }}" class="btn btn-primary" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.edit')">
            <i class="fa fa-edit"></i>
        </a>
        <a href="{{ route('user.index') }}" class="btn btn-default" type="button" data-toggle="tooltip" data-original-title="@lang('user.btn.back')">
            <i class="fa fa-arrow-left"></i>
        </a>
    </div>

</div>
@endsection