app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

Route::get('/', function () {
    if (\Auth::check()) {
        return redirect()->route('dashboard');
    }

    return view('welcome')
        ->withTitle('Laratest');
});

Route::get('test', function () {
    return view('test');
});

Route::auth();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function () {
    Route::put('book/{book}/updateable', 'BookController@updateable')->name('book.updateable');
    Route::post('book/upload/{book}', 'BookController@upload')->name('book.upload');
    Route::resource('book', 'BookController');

    Route::resource('user', 'UserController');
});

resources/views/contents/home.blade.php
@extends('layouts.default')

@section('content')
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">@lang('user.welcome', ['name' => auth()->user()->name])</h3>
    </div>

    <div class="box-body">
        <div class="row">
            <div class="col-lg-6 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>{{ App\User::count() }}</h3>
                        <p>@lang('user.total')</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="{{ route('user.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-6 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>{{ App\Laratest\Book::count() }}</h3>
                        <p>@lang('book.total', ['variable' => 'replacement'])</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="{{ route('book.index') }}" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
        </div>

    </div>

</div>
@endsection